import { Car } from './types';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    make: 'Porsche',
    model: '911 GT3 RS',
    trim: 'Weissach Package',
    year: 2023,
    price: 315000,
    mileage: '1.2k',
    mediaType: 'video',
    mediaUrl: 'https://cdn.coverr.co/videos/coverr-porsche-911-gt3-rs-5079/1080p.mp4',
    posterUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJQSMndXPVXNjLMU0miUrdYAuvZvcxiDYuivXa2MR5eez5UtSHkFpCgfgUPOqh5vACFkVU8bu361mjLT57_t5jRvr6xp1TM9etEa_SXRiIqJXDLHU_kethaI-B7s2K8beRfcoMbPIxMJ10WZp2zFJLlcS5PqgDYiTnVw8TxmrM2zjRdhLBpfi0wiV3RAl95d6LEbNnPady3xM9oZe-M-zrFZ-JsPpcUQr7Dssa6854XUVlVNy8s2W7sxv5a1zZynccr-xY7-pnBEs',
    description: 'Track focused weapon. Weissach package, magnesium wheels, ceramic composite brakes. The ultimate driver\'s car.',
    specs: {
      zeroToSixty: '3.0s',
      horsepower: 518,
      topSpeed: '184 mph',
      engine: '4.0L Flat-6',
    },
    seller: {
      id: 's1',
      name: 'Porsche Center',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAy7gqClAW58Ccww83ap7hXZtLshVJKXj_bdo0H43WvwCwoGJ_Toq2hyRKdrQ2wtjB9Xm3mCVpJv3aCPPAYqcDqFLyJ75lFj3CLBfW4zLR07uqpExgzumCaVdaHTb0pjY9seNmrcl529SWHNd6pKk7iZXuhi1lQ3t7dtK-Uo2IoZyBjRfKK9aec9qYnlpLzzh4dAJIJ9ndVStAyYfcKgttrYVEfTtvLK9kxLFlkzaYVO0hzqWa_4Lj1QKDVJKzVz3j-vEbx-i2tuDs',
    },
    likes: 12400,
    isFeatured: true,
  },
  {
    id: '2',
    make: 'Lamborghini',
    model: 'Revuelto',
    trim: 'V12 Hybrid',
    year: 2024,
    price: 608000,
    mileage: 'Delivery',
    mediaType: 'youtube',
    mediaUrl: 'g2J0_062rFM', // YouTube ID
    posterUrl: 'https://i.ytimg.com/vi/g2J0_062rFM/maxresdefault.jpg',
    description: 'The first HPEV (High Performance Electrified Vehicle) hybrid super sports car. 1015 CV combined power.',
    specs: {
      zeroToSixty: '2.5s',
      horsepower: 1001,
      topSpeed: '217 mph',
      engine: '6.5L V12 + 3 Motors',
    },
    seller: {
      id: 's4',
      name: 'Lambo Newport',
      avatarUrl: 'https://picsum.photos/102/102',
    },
    likes: 21000,
  },
  {
    id: '3',
    make: 'McLaren',
    model: '720S',
    trim: 'Performance',
    year: 2022,
    price: 285000,
    mileage: '3.5k',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=2574&auto=format&fit=crop',
    description: 'Azores Orange with Carbon Black Alcantara. Sports exhaust, stealth pack.',
    specs: {
      zeroToSixty: '2.8s',
      horsepower: 710,
      topSpeed: '212 mph',
    },
    seller: {
      id: 's2',
      name: 'Supercar Vault',
      avatarUrl: 'https://picsum.photos/100/100',
    },
    likes: 8500,
  },
  {
    id: '4',
    make: 'Ferrari',
    model: 'F8 Tributo',
    trim: 'Spider',
    year: 2021,
    price: 345000,
    mileage: '5k',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=2670&auto=format&fit=crop',
    description: 'Rosso Corsa, Cuoio interior. Carbon fibre driver zone + LEDs. Suspension lifter.',
    specs: {
      zeroToSixty: '2.9s',
      horsepower: 710,
      topSpeed: '211 mph',
    },
    seller: {
      id: 's3',
      name: 'Maranello Sales',
      avatarUrl: 'https://picsum.photos/101/101',
    },
    likes: 15200,
  }
];